"""
语言字典
"""
lang_dict_all = {
    'English': {
        'main_1': 'Ready',
        'main_2': '  &Start ',
        'main_3': '  &Edit  ',
        'main_4': ' &Options',
        'main_5': '  &Help  ',
        'main_6': 'Toolbar',
        'label_status_error': 'Error occurred',
        'ui.action_exit_1': 'Quit',
        'ui.action_exit_2': 'Quit the application',
        'ui.action_save_1': 'Export',
        'ui.action_save_2': 'Export table data to file',
        'ui.action_save_3': 'Choose a file to save',
        'ui.action_save_5': 'File saved successfully.',
        'ui.action_save_7': 'Failed to save file.',
        'ui.action_save_8': 'Failed to extract data from the table.',
        'ui.action_update_1': 'Check Updates',
        'ui.action_update_2': 'Check for Updates Online',
        'ui.action_update_3': 'Failed to Check for Updates!',
        'ui.action_update_4': 'New Version Available',
        'ui.action_update_5': 'No Update Needed',
        'ui.action_update_6': 'Current Version: ',
        'ui.action_update_7': 'Latest Version: ',
        'ui.action_update_8': 'Checking for Updates...',
        'ui.action_update_9': 'Update Check Complete',
        'ui.action_unskip_1': 'Unskip',
        'ui.action_unskip_2': 'Remove selected configuration items from the skip list',
        'ui.action_unskip_3': 'Unskip Completed',
        'ui.action_skip_1': 'Skip',
        'ui.action_skip_2': 'Mark selected configuration items as skipped',
        'ui.action_skip_3': 'Added to Skip List Completed',
        'ui.action_about_1': 'About',
        'ui.action_about_2': 'Information about the Software',
        'ui.action_copy_1': 'Copy',
        'ui.action_copy_2': 'Copy Selected Content',
        'ui.action_logs_1': 'View Logs',
        'ui.action_logs_2': 'Open Log Viewer',
        'ui.action_setting_1': 'Program Settings',
        'ui.action_setting_2': 'Open Program Settings Dialog',
        'ui.action_setting_connection_1': 'Connection Settings',
        'ui.action_setting_connection_2': 'Open Database Connection Settings Dialog',
        'ui.action_test_1': 'Test',
        'ui.action_test_2': 'Test Database Connection',
        'ui.action_test_3': 'Test failed, an exception occurred.',
        'ui.action_test_4': 'Environment: ',
        'ui.action_test_5': 'Connection OK!',
        'ui.action_test_6': 'Connection failed!',
        'ui.action_test_7': 'Testing database connection...',
        'ui.action_test_8': 'Test connection completed',
        'ui.action_start_1': 'Run',
        'ui.action_start_2': 'Start execution, fetch configurations from database',
        'ui.action_start_3': 'Querying database...',
        'ui.action_start_4': 'No configurations fetched, please check database connection settings or view the error log.',
        'ui.action_start_5': 'Error occurred while inserting table into data, please check the log for details.',
        'ui.action_start_6': 'Error occurred while prepare data, please check the log for details.',
        'ui.action_start_7': 'A critical error occurred, please view the log in help.',
        'ui.action_start_8': 'Inconsistent',
        'ui.action_start_9': 'Fully',
        'ui.action_start_10': 'Partially',
        'ui.action_start_11': 'No',
        'ui.action_start_12': 'Yes',
        'ui.action_start_13': 'Unknown',
        'ui.table_main_1': 'Name',
        'ui.table_main_2': 'Group',
        'ui.table_main_3': 'Key',
        'ui.table_main_4': 'modified time',
        'ui.table_main_5': 'Consistency',
        'ui.table_main_6': 'Skip',
        'ui.filter_bar_1': 'Filter Name:',
        'ui.filter_bar_2': 'Quick Filter:',
        'ui.filter_bar_3': '--Show All--',
        'ui.filter_bar_4': 'Fully Equal',
        'ui.filter_bar_5': 'Partially Equal',
        'ui.filter_bar_6': 'Skipped',
        'ui.filter_bar_7': 'Invert',
        'ui.filter_bar_8': 'Global Search:',
        'ui.filter_bar_9': 'Search',
        'ui.filter_bar_10': 'Reset',
        'ui.filter_bar_11': 'Entries',
        'ui.dialog_logs_1': 'View Logs',
        'ui.dialog_logs_2': 'Log Level:',
        'ui.dialog_logs_3': 'All',
        'ui.dialog_logs_4': 'Feedback',
        'ui.dialog_logs_5': 'Clear',
        'ui.dialog_logs_6': 'Close',
        'ui.dialog_settings_main_1': 'Settings',
        'ui.dialog_settings_main_2': 'Select Language:',
        'ui.dialog_settings_main_3': 'Select Configuration Center Type:',
        'ui.dialog_settings_main_4': 'Select Apollo Service Name Field:',
        'ui.dialog_settings_main_5': 'Main Settings',
        'ui.dialog_settings_main_6': 'Replace Service Name (Original), split by space:',
        'ui.dialog_settings_main_7': 'Replace Service Name (New), split by space:',
        'ui.dialog_settings_main_8': 'Trim Service Name (Prefix), split by space:',
        'ui.dialog_settings_main_9': 'Trim Service Name (Suffix), split by space:',
        'ui.dialog_settings_main_10': 'Service Name Alignment',
        'ui.dialog_settings_main_11': 'Confirm',
        'ui.dialog_settings_main_12': 'Cancel',
        'ui.dialog_settings_main_13': 'Configuration Saved Successfully!',
        'ui.dialog_settings_main_14': 'Failed to Write Configuration File!',
        'ui.dialog_settings_main_15': 'Changing Language Requires Restart to Take Effect, Restart Now?',
        'ui.dialog_settings_main_16': 'Table Color Switch, turning off can enhance performance:',
        'ui.dialog_settings_connection_1': 'Database Configuration',
        'ui.dialog_settings_connection_2': 'Production',
        'ui.dialog_settings_connection_3': 'Preview',
        'ui.dialog_settings_connection_4': 'Testing',
        'ui.dialog_settings_connection_5': 'Development',
        'ui.dialog_settings_connection_6': 'SSH Tunnel',
        'ui.dialog_settings_connection_7': 'Enable:',
        'ui.dialog_settings_connection_8': 'Address:',
        'ui.dialog_settings_connection_9': 'Port:',
        'ui.dialog_settings_connection_10': 'Username:',
        'ui.dialog_settings_connection_11': 'Password:',
        'ui.dialog_settings_connection_12': 'Database:',
        'ui.dialog_settings_connection_13': 'MySQL Connection',
        'ui.dialog_about_1': 'About',
        'ui.dialog_about_2': 'Configuration Center Comparison Tool',
        'ui.dialog_about_3': 'Version: ',
        'ui.dialog_about_4': 'Author  :',
        'ui.dialog_about_5': 'Website :',
        'ui.dialog_about_6': 'Homepage:',
        'ui.dialog_about_7': """
                <p style="text-align: center; font-size: 16px; font-weight: bold;">Introduction</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;This is a specialized comparison tool for configuration centers, capable of comparing configurations across different clusters, with a basic filtering and search functionality.
                </p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;Currently supported configuration centers and versions:
                </p>
                <p><b>&nbsp;&nbsp;Apollo：</b>2.0.0, 2.1.0</p>
                <p><b>&nbsp;&nbsp;Nacos：</b>v2.1.0</p>
                
                <p style="text-align: center; font-size: 16px; font-weight: bold;">Getting Help</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;Please refer to the project homepage or website for usage instructions before running. If you encounter errors during use, first check the logs for troubleshooting. For bugs and suggestions, please submit an issue on the project homepage.<br>
                </p>
                
                <p style="text-align: center; font-size: 16px; font-weight: bold;">Build Tools</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;ConfigCenterComparer was built using the following tools:
                </p>
                <p><b>&nbsp;&nbsp;Program：</b>Python 3.10.4</p>
                <p><b>&nbsp;&nbsp;Interface：</b>PyQT 5.15.8</p>
                <p><b>&nbsp;&nbsp;Icons：</b><a href='https://icons8.com/'>icons8.com</a></p>
                """
    },
    '中文简体': {
        'main_1': '准备就绪',
        'main_2': '开始(&S)',
        'main_3': '编辑(&E)',
        'main_4': '选项(&O)',
        'main_5': '帮助(&H)',
        'main_6': '工具栏',
        'label_status_error': 'Error occurred',
        'ui.action_exit_1': '退出程序',
        'ui.action_exit_2': '立即退出程序',
        'ui.action_save_1': '导出列表',
        'ui.action_save_2': '导出当前列表到文件',
        'ui.action_save_3': '保存到文件',
        'ui.action_save_5': '文件保存成功',
        'ui.action_save_7': '文件保存失败。',
        'ui.action_save_8': '获取表格数据失败。',
        'ui.action_update_1': '检查更新',
        'ui.action_update_2': '在线检查更新',
        'ui.action_update_3': '检查更新失败！',
        'ui.action_update_4': '有新版发布',
        'ui.action_update_5': '不需要更新',
        'ui.action_update_6': '当前版本：',
        'ui.action_update_7': '最新版本：',
        'ui.action_update_8': '检查更新中...',
        'ui.action_update_9': '检查更新完成',
        'ui.action_unskip_1': '取消忽略',
        'ui.action_unskip_2': '选中配置项从忽略列表中移除',
        'ui.action_unskip_3': '取消忽略完成',
        'ui.action_skip_1': '加入忽略',
        'ui.action_skip_2': '将选中配置项标记为忽略',
        'ui.action_skip_3': '已加入忽略列表',
        'ui.action_about_1': '关于软件',
        'ui.action_about_2': '软件相关信息',
        'ui.action_copy_1': '复制内容',
        'ui.action_copy_2': '复制选择的内容',
        'ui.action_logs_1': '查看日志',
        'ui.action_logs_2': '打开日志文件',
        'ui.action_setting_1': '程序设置',
        'ui.action_setting_2': '打开程序设置对话框',
        'ui.action_setting_connection_1': '连接配置',
        'ui.action_setting_connection_2': '打开数据库连接配置对话框',
        'ui.action_test_1': '测试连接',
        'ui.action_test_2': '测试数据库连接',
        'ui.action_test_3': '测试失败，发生异常。',
        'ui.action_test_4': '环境：',
        'ui.action_test_5': '连接成功！',
        'ui.action_test_6': '连接失败！',
        'ui.action_test_7': '测试数据库连接中...',
        'ui.action_test_8': '测试连接完成',
        'ui.action_start_1': '开始运行',
        'ui.action_start_2': '开始运行，从数据库中获取配置',
        'ui.action_start_3': '正在查询数据库...',
        'ui.action_start_4': '没有获取到任何配置，请检查数据库连接设置或查看错误日志。',
        'ui.action_start_5': '把列表插入数据时出现错误，请在帮助中查看日志。',
        'ui.action_start_6': '合成表格数据失败，请在帮助中查看日志。',
        'ui.action_start_7': '运行发生严重错误，请在帮助中查看日志。',
        'ui.action_start_8': '不一致',
        'ui.action_start_9': '完全一致',
        'ui.action_start_10': '部分一致',
        'ui.action_start_11': '否',
        'ui.action_start_12': '是',
        'ui.action_start_13': '未知状态',
        'ui.table_main_1': '服务',
        'ui.table_main_2': '分组',
        'ui.table_main_3': '配置键',
        'ui.table_main_4': '修改时间',
        'ui.table_main_5': '一致性',
        'ui.table_main_6': '忽略',
        'ui.filter_bar_1': '过滤服务：',
        'ui.filter_bar_2': '快速过滤：',
        'ui.filter_bar_3': '--显示所有--',
        'ui.filter_bar_4': '完全一致',
        'ui.filter_bar_5': '部分一致',
        'ui.filter_bar_6': '已忽略',
        'ui.filter_bar_7': '反选',
        'ui.filter_bar_8': '全局搜索：',
        'ui.filter_bar_9': '搜索',
        'ui.filter_bar_10': '重置',
        'ui.filter_bar_11': '条配置',
        'ui.dialog_logs_1': '查看日志',
        'ui.dialog_logs_2': '日志等级：',
        'ui.dialog_logs_3': '所有',
        'ui.dialog_logs_4': '提交反馈',
        'ui.dialog_logs_5': '清空',
        'ui.dialog_logs_6': '关闭',
        'ui.dialog_settings_main_1': '设置页面',
        'ui.dialog_settings_main_2': '选择语言：',
        'ui.dialog_settings_main_3': '选择配置中心类型：',
        'ui.dialog_settings_main_4': '选择 Apollo 服务名字段：',
        'ui.dialog_settings_main_5': '主设置',
        'ui.dialog_settings_main_6': '替换服务名（原名），按空格分词：',
        'ui.dialog_settings_main_7': '替换服务名（新名），按空格分词：',
        'ui.dialog_settings_main_8': '裁剪服务名（前缀），按空格分词：',
        'ui.dialog_settings_main_9': '裁剪服务名（后缀），按空格分词：',
        'ui.dialog_settings_main_10': '服务名对齐',
        'ui.dialog_settings_main_11': '确认',
        'ui.dialog_settings_main_12': '取消',
        'ui.dialog_settings_main_13': '配置保存成功',
        'ui.dialog_settings_main_14': '写入配置文件失败！',
        'ui.dialog_settings_main_15': '修改语言需要重启软件才生效，立即重启吗？',
        'ui.dialog_settings_main_16': '表格颜色开关，关闭可提升运行速度：',
        'ui.dialog_settings_connection_1': '数据库配置',
        'ui.dialog_settings_connection_2': '生产环境',
        'ui.dialog_settings_connection_3': '预览环境',
        'ui.dialog_settings_connection_4': '测试环境',
        'ui.dialog_settings_connection_5': '开发环境',
        'ui.dialog_settings_connection_6': 'SSH 隧道配置',
        'ui.dialog_settings_connection_7': '启用：',
        'ui.dialog_settings_connection_8': '地址：',
        'ui.dialog_settings_connection_9': '端口：',
        'ui.dialog_settings_connection_10': '用户名：',
        'ui.dialog_settings_connection_11': '密码：',
        'ui.dialog_settings_connection_12': '库名：',
        'ui.dialog_settings_connection_13': 'MySQL 连接配置',
        'ui.dialog_about_1': '关于',
        'ui.dialog_about_2': '配置中心对比工具',
        'ui.dialog_about_3': '版本：',
        'ui.dialog_about_4': '作者：',
        'ui.dialog_about_5': '网站：',
        'ui.dialog_about_6': '主页：',
        'ui.dialog_about_7': """
                <p style="text-align: center; font-size: 16px; font-weight: bold;">程序简介</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;这是一个配置中心专用对比工具，可支持不同集群中配置对比，并带有简单过滤搜索功能。
                </p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;目前支持配置中心和版本：
                </p>
                <p><b>&nbsp;&nbsp;Apollo：</b>2.0.0、2.1.0</p>
                <p><b>&nbsp;&nbsp;Nacos：</b>v2.1.0</p>

                <p style="text-align: center; font-size: 16px; font-weight: bold;">获取帮助</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;运行前请查阅项目主页或网站中使用说明。如使用中遇到错误，可先查看日志自行排错。Bug 和建议请到项目主页提交 issue。<br>
                </p>

                <p style="text-align: center; font-size: 16px; font-weight: bold;">构建工具</p>
                <p style="text-align: justify;">
                &nbsp;&nbsp;ConfigCenterComparer 构建用到以下工具：
                </p>
                <p><b>&nbsp;&nbsp;程序：</b>Python 3.10.4</p>
                <p><b>&nbsp;&nbsp;界面：</b>PyQT 5.15.8</p>
                <p><b>&nbsp;&nbsp;图标：</b><a href='https://icons8.com/'>icons8.com</a></p>
                """,
    },
}
